name: Update Financial Data

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install yfinance requests pandas

      - name: Run Analysis
        run: |
          python calculate_stocks.py
          python calculate_crypto.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/*.json
          git add data_crypto/*.json
          git commit -m "Automated Data Update" || exit 0
          git push
